### ISSUE TITLE
deploy script

### ISSUE THREAD

**Issue by caseyjlaw** [realtimeradio/caltech-lwa#20]
OVRO-LWA is working on a code deployment scheme to improve reliability. Rick's lwa-shell allows multiple repos to be checked out at specific versions and installed at the same time.
We're working on integrating software on cal-im into this scheme. All cal-im user code (including lwa_f client) should be installable with a single script called "deploy". Here's one that could work for caltech-lwa:

```
#!/bin/bash
set -ex

echo $HOSTNAME  # should be installing on calim
echo $PWD  # should be base of code repo
whoami  # should be user pipeline (or ubuntu?)

# setup
DATE=$(date --iso-8601=seconds)
LOG=~/deploy_caltech-lwa_$DATE.log

if [[ $HOSTNAME =~ 'calim' ]]; then
    echo "$DATE" >> $LOG 2>>$LOG
    conda run -n datarecorder which python >> $LOG 2>>$LOG
    conda run -n datarecorder git describe --abbrev=8 --long --tags >> $LOG 2>>$LOG
    cd control_sw
    conda run -n datarecorder pip install . >> $LOG 2>>$LOG
else
    echo "Not installing on this host"
fi
```

Any objections to adding this as an executable `deploy` in the base directory?
Related: did we decide that breaking out lwa_f python code was not worth it?

**Comment by jack-h** [comment]
Done!
